# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(31, 180, 75, 23))
        self.seven.setObjectName("seven")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(31, 209, 75, 23))
        self.four.setIconSize(QtCore.QSize(30, 30))
        self.four.setObjectName("four")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(31, 238, 75, 23))
        self.one.setObjectName("one")
        self.negative = QtWidgets.QPushButton(self.centralwidget)
        self.negative.setGeometry(QtCore.QRect(31, 267, 75, 23))
        self.negative.setObjectName("negative")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(112, 267, 75, 23))
        self.zero.setIconSize(QtCore.QSize(20, 20))
        self.zero.setObjectName("zero")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(112, 180, 75, 23))
        self.eight.setObjectName("eight")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(112, 238, 75, 23))
        self.two.setObjectName("two")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(112, 209, 75, 23))
        self.five.setObjectName("five")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(193, 267, 75, 23))
        self.dot.setObjectName("dot")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(193, 180, 75, 23))
        self.nine.setObjectName("nine")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(193, 238, 75, 23))
        self.three.setObjectName("three")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(193, 209, 75, 23))
        self.six.setObjectName("six")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(274, 267, 75, 23))
        self.equal.setObjectName("equal")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(274, 180, 75, 23))
        self.multiply.setObjectName("multiply")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(274, 238, 75, 23))
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(274, 209, 75, 23))
        self.minus.setObjectName("minus")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(274, 151, 75, 23))
        self.divide.setObjectName("divide")
        self.right_paranthesis = QtWidgets.QPushButton(self.centralwidget)
        self.right_paranthesis.setGeometry(QtCore.QRect(112, 151, 75, 23))
        self.right_paranthesis.setObjectName("right_paranthesis")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(193, 151, 75, 23))
        self.percent.setObjectName("percent")
        self.left_paranthesis = QtWidgets.QPushButton(self.centralwidget)
        self.left_paranthesis.setGeometry(QtCore.QRect(31, 151, 75, 23))
        self.left_paranthesis.setObjectName("left_paranthesis")
        self.input = QtWidgets.QTextBrowser(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(40, 30, 221, 111))
        self.input.setObjectName("input")
        self.input.setFontPointSize(14)
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(270, 30, 71, 111))
        self.result.setObjectName("result")
        self.result.setFontPointSize(14)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(30, 300, 321, 23))
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.negative.clicked.connect(self.data_negative)
        self.zero.clicked.connect(self.data_zero)
        self.dot.clicked.connect(self.data_dot)
        self.equal.clicked.connect(self.data_equal)
        self.one.clicked.connect(self.data_one)
        self.two.clicked.connect(self.data_two)
        self.three.clicked.connect(self.data_three)
        self.plus.clicked.connect(self.data_plus)
        self.four.clicked.connect(self.data_four)
        self.five.clicked.connect(self.data_five)
        self.six.clicked.connect(self.data_six)
        self.minus.clicked.connect(self.data_minus)
        self.seven.clicked.connect(self.data_seven)
        self.eight.clicked.connect(self.data_eight)
        self.nine.clicked.connect(self.data_nine)
        self.multiply.clicked.connect(self.data_multiply)
        self.divide.clicked.connect(self.data_divide)
        self.percent.clicked.connect(self.data_percent)
        self.right_paranthesis.clicked.connect(self.data_right_paranthesis)
        self.left_paranthesis.clicked.connect(self.data_left_paranthesis)
        self.clear.clicked.connect(self.data_clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def data_negative(self):
        self.input.insertPlainText('(-')
    def data_zero(self):
        self.input.insertPlainText('0')
    def data_dot(self):
        self.input.insertPlainText('.')
    def data_one(self):
        self.input.insertPlainText('1')
    def data_two(self):
        self.input.insertPlainText('2')
    def data_three(self):
        self.input.insertPlainText('3')
    def data_plus(self):
        self.input.insertPlainText('+')
    def data_four(self):
        self.input.insertPlainText('4')
    def data_five(self):
        self.input.insertPlainText('5')
    def data_six(self):
        self.input.insertPlainText('6')
    def data_minus(self):
        self.input.insertPlainText('-')
    def data_seven(self):
        self.input.insertPlainText('7')
    def data_eight(self):
        self.input.insertPlainText('8')
    def data_nine(self):
        self.input.insertPlainText('9')
    def data_multiply(self):
        self.input.insertPlainText('*')
    def data_divide(self):
        self.input.insertPlainText('/')
    def data_percent(self):
        self.input.insertPlainText('*(1/100)')
    def data_right_paranthesis(self):
        self.input.insertPlainText(')')
    def data_left_paranthesis(self):
        self.input.insertPlainText('(')
    def data_equal(self):
        statement = self.input.toPlainText()
        self.result.insertPlainText(str(eval(statement)))
    def data_clear(self):
        self.input.clear()
        self.result.clear()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.four.setText(_translate("MainWindow", "4"))
        self.one.setText(_translate("MainWindow", "1"))
        self.negative.setText(_translate("MainWindow", "+/-"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.two.setText(_translate("MainWindow", "2"))
        self.five.setText(_translate("MainWindow", "5"))
        self.dot.setText(_translate("MainWindow", "."))
        self.nine.setText(_translate("MainWindow", "9"))
        self.three.setText(_translate("MainWindow", "3"))
        self.six.setText(_translate("MainWindow", "6"))
        self.equal.setText(_translate("MainWindow", "="))
        self.multiply.setText(_translate("MainWindow", "×"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "÷"))
        self.right_paranthesis.setText(_translate("MainWindow", ")"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.left_paranthesis.setText(_translate("MainWindow", "("))
        self.clear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
